# -*- coding: utf-8 -*-
"""Analise exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yeUD1LOzfRXQz2SvxSfPg-4KKb2iKJga
"""

!pip install sweetviz
!pip install xlrd==1.2.0

import pandas as pd    
import sweetviz as sv
import numpy as np

tabela = pd.read_excel('basededados.xls')

display(tabela.info())

tabela = tabela.drop(['Codigo EAN', 'Unnamed: 1', 'DATA' , 'Cod.', 'Total Investido', 'Vendas'], axis=1)

display(tabela.info())

tabela.dropna(how='all', axis=1)
tabela.dropna(how='any', axis=0)
display(tabela.info())

tabela['Radio'] = pd.to_numeric(tabela['Radio'], errors='coerce')
display(tabela.info())

report = sv.analyze(tabela)

report.show_html()

comp = np.random.rand(len(tabela)) < 230
comp2 = np.random.rand(len(tabela)) < 150
treino = tabela[comp]
teste = tabela[comp2]

display(treino.head())

display(teste.head())

report2 = sv.compare([treino, 'training_set'], [teste, 'testing_set'])

report2.show_html()