# -*- coding: utf-8 -*-
"""Codigos para realizar analize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tAwlIM8tUMzrxRQ-R0zM_bUQi7EC-1J8
"""

!pip install xlrd==1.2.0

import pandas as pd 

#Lendo a tabela basededados.xls
tabela = pd.read_excel('basededados.xls')
display(tabela)

#Mostrando os 25 primeiros registros de dados da tabela de cada coluna
display(tabela.head(25))

#Pegando um intervalo de dados entre TV e Facebook
tabela.loc[15:40, 'DATA':'Facebook']

#Mostrando as informacoes das colunas das tabelas 
tabela.info()

#Mostrando a correlacao dos dados da tabela 
display(tabela.corr())

#Pegando 2 intervalos de dados para representar entre DATA e Jornal
tabela = tabela.iloc[15:40, 2:8]

display(tabela)

#Mostrando dados da coluna TV 
display(tabela[['TV']])

#Mostrando dados das colunas TV e Radio
display(tabela[['TV', 'Radio']])

#Mostrando dados por intervalo de valores de 2 colunas TV e Instagram
display(tabela[(tabela.TV <= 50) & (tabela.Instagram >= 24)])

#Mostrando dados por intervalo de uma coluna Vendas 
display(tabela[tabela.Vendas < 400])

#Ordenando dados em ordem crescente
display(tabela.sort_values(by = ['TV']))

#Selecionando apenas os 10 primeiros registros da tabela e armazenando eles
tabela = tabela.head(10)

display(tabela)

#Importando tabela dados em formato csv com separador para todas as colunas que estiverem com ;
tabela2 = pd.read_csv('dados.csv', sep=';')

display(tabela2)

#Descricao classificando os valores altos , baixos e medias dos dados da tabela de cada coluna
display(tabela.describe())

#Descricao de todos os valores maximos da tabela de cada coluna
display(tabela.max())

#Descricao de todos os valores minimos da tabela de cada coluna
display(tabela.min())

#Descricao de todas as medias dos valores da tabela de cada coluna
display(tabela.mean())

#Ordendando os dados em ordem crescente
ordem_crescente = tabela.sort_values(by=['TV'], ascending=[True])

display(ordem_crescente)

#Ordendando os dados em ordem decrescente
ordem_decrescente = tabela.sort_values(by=['TV'], ascending=[False])

display(ordem_decrescente)

#Realizando uma contagem na tabela e identificando o valor que mais aparece nas celulas da tabela
display(tabela[['TV']].value_counts)

#Agrupando os valores das colunas Facebook e TV e representando os valores agrupados como valor maximo, minimo, media e mediana
dados = tabela.groupby(['Facebook'])['TV'].agg(['max', 'min', 'mean', 'median'])

display(dados)