# -*- coding: utf-8 -*-
"""Items para Consulta na Analise Preditiva.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fG0lTjEXrsGFUjItsgIjaslaj80vuue8
"""

##Biblioteca para treino de dados da tabela e realizar previsoes

#from sklearn.ensemble import HistGradientBoostingRegressor

#modelo_histgdt = HistGradientBoostingRegressor()
#modelo_histgdt.fit(x_treino, y_treino)
#previsao_histgdt = modelo_histgdt.predict(x_teste)

#--------------------------------------------------------------
##Biblioteca para obter o score preciso da previsao 

#from sklearn.metrics import accuracy_score

#medir = accuracy_score(y_teste, previsao)

#--------------------------------------------------------------
##Graficos de Seaborn 

#sns.lineplot(data=tabela_auxiliar)
#sns.FacetGrid(data=tabela_auxiliar)
#sns.PairGrid(data=tabela_auxiliar)
#sns.clustermap(data=tabela_auxiliar)
#sns.displot(data=tabela_auxiliar)
#sns.histplot(data=tabela_auxiliar)
#sns.relplot(data=tabela_auxiliar)
#sns.scatterplot(data=tabela_auxiliar)
#sns.kdeplot(data=tabela_auxiliar)
#sns.catplot(data=tabela_auxiliar)
#sns.barplot(data=tabela_auxiliar)

#--------------------------------------------------------------
##Importando tabela excel em formato csv com separador de ; para cada coluna da tabela

#tabela = pd.read_csv('tabela.csv', sep=';')
#display(tabela)